using System;
using System.Collections.Generic;
using System.Linq;

namespace CryptoAITerminal.TerminalUI.Services;

public enum UiLanguage
{
    English,
    Russian
}

public sealed class UiLocalizationService
{
    private readonly Dictionary<string, string> _englishToRussian = new(StringComparer.Ordinal)
    {
        ["Syncing market feeds..."] = "Синхронизация рыночных потоков...",
        ["Booting strategy engine..."] = "Запуск движка стратегий...",
        ["Linking risk controls..."] = "Подключение контроля риска...",
        ["Preparing live workspace..."] = "Подготовка рабочего пространства...",
        ["Workspace online"] = "Рабочее пространство готово",
        ["Connecting"] = "Подключение",
        ["Connected"] = "Подключено",
        ["CONNECTING"] = "ПОДКЛЮЧЕНИЕ",
        ["LIVE DATA"] = "ЖИВЫЕ ДАННЫЕ",
        ["FLAT"] = "НЕТ ПОЗИЦИИ",
        ["Bullish"] = "Бычий",
        ["Defensive"] = "Осторожный",
        ["Waiting for live market context"] = "Ожидание живого рыночного контекста",
        ["Connect to a symbol to see a suggested entry zone, stop and target."] = "Подключите инструмент, чтобы увидеть предлагаемую зону входа, стоп и цель.",
        ["Waiting for market data"] = "Ожидание рыночных данных",
        ["Execution guard on"] = "Защита исполнения включена",
        ["Live routing enabled"] = "Живое исполнение включено",
        ["PLACE SELL ORDER"] = "РАЗМЕСТИТЬ ОРДЕР SELL",
        ["SELL MARKET"] = "ПРОДАТЬ ПО РЫНКУ",
        ["PLACE BUY ORDER"] = "РАЗМЕСТИТЬ ОРДЕР BUY",
        ["BUY MARKET"] = "КУПИТЬ ПО РЫНКУ",
        ["Set price and quantity to prepare the ticket."] = "Укажите цену и объём, чтобы подготовить заявку.",
        ["No working orders to cancel."] = "Нет рабочих ордеров для отмены.",
        ["DOM recentered and locked to current price."] = "DOM отцентрирован и привязан к текущей цене.",
        ["DOM unlocked for manual scroll."] = "DOM разблокирован для ручной прокрутки.",
        ["ACTIVE"] = "АКТИВЕН",
        ["WAIT"] = "ОЖИДАНИЕ",
        ["LAST"] = "ПОСЛ.",
        ["BUY"] = "ПОКУПКА",
        ["SELL"] = "ПРОДАЖА",
        ["BUY NOW"] = "КУПИТЬ",
        ["Order Entry"] = "Ввод ордера",
        ["Order Book"] = "Стакан заявок",
        ["Visible buy and sell requests by level"] = "Видимые заявки на покупку и продажу по уровням",
        ["Price"] = "Цена",
        ["Size"] = "Объём",
        ["Best Bid"] = "Лучший bid",
        ["Best Ask"] = "Лучший ask",
        ["Spread"] = "Спред",
        ["Price Chart"] = "График цены",
        ["Order Placed"] = "Ордер размещён",
        ["Recent Activity"] = "Последняя активность",
        ["Order ID"] = "ID ордера",
        ["Status"] = "Статус",
        ["Activity & Logs"] = "Активность и логи",
        ["All runtime messages in one scrollable surface."] = "Все сообщения выполнения в одной прокручиваемой области.",
        ["SYSTEM OUTPUT"] = "СИСТЕМНЫЙ ВЫВОД",
        ["Venue"] = "Площадка",
        ["Quote Currency"] = "Валюта котировки",
        ["Global Sizing"] = "Глобальный размер позиции",
        ["% of Equity"] = "% от капитала",
        ["Risk Mode"] = "Режим риска",
        ["Account Equity"] = "Капитал счёта",
        ["24h PnL"] = "PnL за 24ч",
        ["Active Symbol"] = "Активный инструмент",
        ["Symbol"] = "Инструмент",
        ["Position"] = "Позиция",
        ["Entry"] = "Вход",
        ["Last Price"] = "Последняя цена",
        ["High"] = "Максимум",
        ["Low"] = "Минимум",
        ["Volume"] = "Объём",
        ["Current timeframe"] = "Текущий таймфрейм",
        ["Last candle"] = "Последняя свеча",
        ["Positions & Orders"] = "Позиции и ордера",
        ["Position Summary"] = "Сводка по позиции",
        ["All"] = "Все",
        ["Orders"] = "Ордеры",
        ["Fills"] = "Сделки",
        ["Signals"] = "Сигналы",
        ["ID"] = "ID",
        ["SIDE"] = "СТОРОНА",
        ["TYPE"] = "ТИП",
        ["QTY"] = "КОЛ-ВО",
        ["FILLED"] = "ИСПОЛНЕНО",
        ["TIF"] = "TIF",
        ["CREATED"] = "СОЗДАН",
        ["TIME"] = "ВРЕМЯ",
        ["SETUP"] = "СЕТАП",
        ["TARGET"] = "ЦЕЛЬ",
        ["STOP"] = "СТОП",
        ["UNREALIZED PNL"] = "НЕРЕАЛ. PNL",
        ["PNL %"] = "PNL %",
        ["MARGIN"] = "МАРЖА",
        ["ROE"] = "ROE",
        ["Total Unrealized PnL"] = "Общий нереализованный PnL",
        ["View All Positions"] = "Смотреть все позиции",
        ["View All Orders"] = "Смотреть все ордера",
        ["No working orders yet. Arm a limit, TP or SL to populate the blotter."] = "Рабочих ордеров пока нет. Установите лимит, TP или SL, чтобы заполнить таблицу.",
        ["No fills yet. Execution tape will appear here after the first order."] = "Сделок пока нет. Лента исполнения появится после первого ордера.",
        ["No open positions. Use the ticket to open the first trade."] = "Открытых позиций пока нет. Используйте заявку, чтобы открыть первую сделку.",
        ["Signals are waiting for stronger market structure before activating."] = "Сигналы ждут более сильной рыночной структуры перед активацией.",
        ["Recent actions, routed orders and state changes will appear here."] = "Последние действия, маршрутизированные ордеры и изменения состояния появятся здесь.",
        ["AI BOT"] = "AI BOT",
        ["Trade Plan"] = "Торговый план",
        ["Key Levels (USDT)"] = "Ключевые уровни (USDT)",
        ["Resistance R2"] = "Сопротивление R2",
        ["Resistance R1"] = "Сопротивление R1",
        ["Current Price"] = "Текущая цена",
        ["Support S1"] = "Поддержка S1",
        ["Support S2"] = "Поддержка S2",
        ["Direction"] = "Направление",
        ["Timeframe"] = "Таймфрейм",
        ["Valid For"] = "Актуально",
        ["Stop Loss"] = "Стоп-лосс",
        ["Take Profit 1"] = "Тейк-профит 1",
        ["Take Profit 2"] = "Тейк-профит 2",
        ["Risk / Reward"] = "Риск / Доходность",
        ["Position Size"] = "Размер позиции",
        ["Warnings"] = "Предупреждения",
        ["Ask AI Bot..."] = "Спросить AI Bot...",
        ["AI responses are informational only, not financial advice."] = "Ответы AI носят информационный характер и не являются финансовой рекомендацией.",
        ["DEX Ticket"] = "DEX заявка",
        ["SEARCH"] = "ПОИСК",
        ["REFRESH"] = "ОБНОВИТЬ",
        ["Quote Asset"] = "Котируемый актив",
        ["Sell"] = "Продажа",
        ["BUY TOKEN"] = "КУПИТЬ ТОКЕН",
        ["SELL TOKEN"] = "ПРОДАТЬ ТОКЕН",
        ["DEX Market Snapshot"] = "Снимок DEX рынка",
        ["Price USD"] = "Цена USD",
        ["Liquidity"] = "Ликвидность",
        ["Market Overview"] = "Обзор рынка",
        ["MARKET OVERVIEW"] = "ОБЗОР РЫНКА",
        ["Tracked Coins"] = "Отслеживаемые монеты",
        ["Click any coin to open its chart and order book."] = "Нажмите на любую монету, чтобы открыть её график и стакан.",
        ["Help"] = "Помощь",
        ["Logout"] = "Выход",
        ["Launching the AI-driven trading workspace"] = "Запуск AI-рабочего пространства для торговли",
        ["DEX streams"] = "DEX потоки",
        ["Risk engine"] = "Риск-движок",
        ["AI signals"] = "AI сигналы",
        ["CEX"] = "CEX",
        ["DEX"] = "DEX",
        ["Dashboard"] = "Дашборд",
        ["Markets"] = "Рынки",
        ["Trading"] = "Торговля",
        ["AI Signals"] = "AI Сигналы",
        ["AI SIGNAL STUDIO"] = "AI SIGNAL STUDIO",
        ["Bots"] = "Боты",
        ["Portfolio"] = "Портфель",
        ["Risk"] = "Риск",
        ["Analytics"] = "Аналитика",
        ["Settings"] = "Настройки",
        ["Backtest"] = "Бэктест",
        ["Sniper Coins"] = "Снайпер монет",
        ["Crypto Copilot Workspace"] = "Рабочее пространство крипто-ассистента",
        ["A focused signal desk with local crypto chat, visual review, route context, and quick action prompts built around the live terminal state."] = "Центр сигналов с локальным крипто-чатом, визуальным разбором, контекстом маршрута и быстрыми действиями на основе текущего состояния терминала.",
        ["Chat"] = "Чат",
        ["Visuals"] = "Визуалы",
        ["Engine"] = "Движок",
        ["Status"] = "Статус",
        ["Prompt Library"] = "Библиотека промптов",
        ["Scope"] = "Контекст",
        ["Model Slot"] = "Слот модели",
        ["Context Venue"] = "Источник контекста",
        ["Context Sources"] = "Источники контекста",
        ["AI desk follows terminal venue"] = "AI-панель следует за площадкой терминала",
        ["Independent AI context override"] = "Независимый override контекста AI",
        ["Prompt Builder"] = "Конструктор промпта",
        ["BUILD PROMPT"] = "СОБРАТЬ ПРОМПТ",
        ["Saved Presets"] = "Сохранённые пресеты",
        ["My Preset Name"] = "Имя моего пресета",
        ["SAVE MY PRESET"] = "СОХРАНИТЬ МОЙ ПРЕСЕТ",
        ["My Presets"] = "Мои пресеты",
        ["Your own saved prompt profiles live here and persist between terminal restarts."] = "Здесь живут ваши собственные профили промптов, и они сохраняются между перезапусками терминала.",
        ["LOAD"] = "ЗАГРУЗИТЬ",
        ["BUILD"] = "СОБРАТЬ",
        ["SEND NOW"] = "ОТПРАВИТЬ СРАЗУ",
        ["DELETE"] = "УДАЛИТЬ",
        ["One-click tactical profiles for scalp, swing, DEX, sniper, and risk review workflows."] = "Тактические профили в один клик для scalp, swing, DEX, sniper и сценариев риск-разбора.",
        ["Assemble a focused AI question from the active context, trade style, horizon, risk, and analysis goal."] = "Соберите точный AI-вопрос из активного контекста, стиля сделки, горизонта, риска и цели анализа.",
        ["Asset"] = "Актив",
        ["Trade Style"] = "Стиль сделки",
        ["Horizon"] = "Горизонт",
        ["Risk Profile"] = "Профиль риска",
        ["Focus"] = "Фокус",
        ["Preset Summary"] = "Сводка пресета",
        ["Prompt Preview"] = "Предпросмотр промпта",
        ["Image Window"] = "Окно изображений",
        ["Live Context"] = "Живой контекст",
        ["Knowledge Base"] = "База знаний",
        ["Conversation"] = "Диалог",
        ["Use this desk like an execution copilot: ask for setup, invalidation, route checks, sniper pressure, glossary topics, or a concrete next action."] = "Используйте этот экран как ассистента исполнения: спрашивайте о сетапе, инвалидации, проверке маршрута, давлении sniper-модуля, базовых терминах или следующем конкретном действии.",
        ["Ask about the setup, risk, route, sniper state, or request a visual breakdown..."] = "Спросите о сетапе, риске, маршруте, состоянии sniper-модуля или запросите визуальный разбор...",
        ["SEND"] = "ОТПРАВИТЬ",
        ["SYNC CONTEXT"] = "СИНХР. КОНТЕКСТ",
        ["BUILD PLAN"] = "СОБРАТЬ ПЛАН",
        ["ANALYZE VISUAL"] = "РАЗОБРАТЬ ВИЗУАЛ",
        ["CLEAR"] = "ОЧИСТИТЬ",
        ["Pinned Visual"] = "Закреплённый визуал",
        ["Signal Metric"] = "Метрика сигнала",
        ["Visual Usage"] = "Как использовать визуал",
        ["Use the gallery below to pin a chart-style image, then run visual analysis to get a local explanation tied to current market and route state."] = "Выберите изображение из галереи ниже, закрепите его и запустите визуальный разбор, чтобы получить локальное объяснение, связанное с текущим рынком и состоянием маршрута.",
        ["Visual Rail"] = "Лента визуалов",
        ["tap to focus"] = "нажмите для выбора",
        ["GPT SLOT RESERVED"] = "СЛОТ GPT ЗАРЕЗЕРВИРОВАН",
        ["LIVE-AWARE COPILOT"] = "ЛОКАЛЬНЫЙ КРИПТО-ПОМОЩНИК",
        ["LOCAL DESK MODE"] = "ЛОКАЛЬНЫЙ РЕЖИМ",
        ["ANSWER READY"] = "ОТВЕТ ГОТОВ",
        ["CONTEXT UPDATED"] = "КОНТЕКСТ ОБНОВЛЁН",
        ["PROMPT BUILT"] = "ПРОМПТ СОБРАН",
        ["PRESET LOADED"] = "ПРЕСЕТ ЗАГРУЖЕН",
        ["MY PRESET SAVED"] = "МОЙ ПРЕСЕТ СОХРАНЁН",
        ["MY PRESET DELETED"] = "МОЙ ПРЕСЕТ УДАЛЁН",
        ["PRESET SENT"] = "ПРЕСЕТ ОТПРАВЛЕН",
        ["Local visuals ready"] = "Локальные визуалы готовы",
        ["Explain setup"] = "Объяснить сетап",
        ["Risk check"] = "Проверка риска",
        ["DEX route"] = "DEX маршрут",
        ["Sniper pulse"] = "Пульс sniper",
        ["Visual read"] = "Разбор визуала",
        ["Next action"] = "Следующее действие",
        ["Entry / Exit"] = "Вход / Выход",
        ["Buy now or wait"] = "Войти сейчас или ждать",
        ["Scalp map"] = "Scalp-план",
        ["Stop / Target"] = "Стоп / Цели",
        ["Position plan"] = "План позиции",
        ["Coin review"] = "Разбор монеты",
        ["Take profit ladder"] = "Лесенка фиксации",
        ["Invalidation check"] = "Проверка инвалидации",
        ["DEX entry safety"] = "Безопасность DEX-входа",
        ["Route blocker"] = "Блокер маршрута",
        ["Fresh pair check"] = "Проверка новой пары",
        ["Slot pressure"] = "Давление по слотам",
        ["Chart read"] = "Разбор графика",
        ["Visual risk map"] = "Карта риска по визуалу",
        ["Spot Entry"] = "Спот-вход",
        ["Swing Entry"] = "Свинг-вход",
        ["Scalp"] = "Скальп",
        ["Breakout"] = "Пробой",
        ["Pullback"] = "Откат",
        ["DEX Buy"] = "DEX-покупка",
        ["Sniper Review"] = "Sniper-разбор",
        ["Intraday"] = "Внутри дня",
        ["1-2 Days"] = "1-2 дня",
        ["Swing"] = "Свинг",
        ["Event Driven"] = "Событийный",
        ["Conservative"] = "Консервативный",
        ["Balanced"] = "Сбалансированный",
        ["Aggressive"] = "Агрессивный",
        ["Entry Timing"] = "Тайминг входа",
        ["Exit Timing"] = "Тайминг выхода",
        ["Risk Map"] = "Карта риска",
        ["Setup Quality"] = "Качество сетапа",
        ["DEX Safety"] = "Безопасность DEX",
        ["Sniper Readiness"] = "Готовность sniper",
        ["Scalp BTC"] = "Scalp BTC",
        ["Fast BTC intraday scalp with timing and invalidation focus."] = "Быстрый внутридневной BTC-scalp с фокусом на тайминг и инвалидацию.",
        ["Swing ETH"] = "Swing ETH",
        ["Higher-timeframe ETH setup with clean entries and exits."] = "ETH-сетап старшего таймфрейма с чистыми входами и выходами.",
        ["DEX Degen"] = "DEX Degen",
        ["Aggressive DEX token review with safety and route focus."] = "Агрессивный разбор DEX-токена с фокусом на безопасность и маршрут.",
        ["Sniper Filter"] = "Sniper Filter",
        ["Selective new-pair screening with slot pressure awareness."] = "Избирательный фильтр новых пар с учётом давления по слотам.",
        ["Risk Review"] = "Risk Review",
        ["Position sizing, invalidation, and exit ladder review."] = "Разбор размера позиции, инвалидации и лесенки выхода.",
        ["Slippage"] = "Проскальзывание",
        ["Execution"] = "Исполнение",
        ["Limit vs Market"] = "Лимит против рынка",
        ["DEX Safety"] = "Безопасность DEX",
        ["New Pair Filter"] = "Фильтр новых пар",
        ["Desk Copilot"] = "Локальный ассистент",
        ["Local runtime context"] = "Локальный контекст терминала",
        ["I read the live terminal state and answer from your local market, risk, DEX, and sniper context. Ask for setup, invalidation, route, or visual breakdowns."] = "Я читаю текущее состояние терминала и отвечаю на основе локального контекста рынка, риска, DEX и sniper-модуля. Спрашивайте о сетапе, инвалидации, маршруте или визуальном разборе.",
        ["Offline crypto knowledge cards for execution, risk, DEX flow, and new-pair safety checks."] = "Офлайн-карточки знаний по исполнению, риску, DEX-маршрутам и проверке безопасности новых пар.",
        ["What is slippage and how should I think about it in this terminal?"] = "Что такое проскальзывание и как смотреть на него в этом терминале?",
        ["When should I use a limit order instead of a market order?"] = "Когда лучше использовать лимитный ордер вместо рыночного?",
        ["How should I place a stop loss on a crypto setup?"] = "Как правильно ставить стоп-лосс в крипто-сетапе?",
        ["What should I verify before trading a fresh DEX token?"] = "Что нужно проверить перед торговлей свежим DEX-токеном?",
        ["What makes a new pair worth watching instead of chasing?"] = "Что делает новую пару достойной наблюдения вместо погони за ней?",
        ["Market Structure"] = "Структура рынка",
        ["Risk Map"] = "Карта риска",
        ["DEX Route Flow"] = "DEX-маршрут",
        ["Sniper Heat"] = "Sniper-поток",
        ["SESSION RESET"] = "СЕССИЯ СБРОШЕНА",
        ["Market Sync"] = "Синхронизация рынка",
        ["context refresh"] = "обновление контекста",
        ["Synced"] = "Синхр.",
        ["MARKET CONTEXT SYNCED"] = "КОНТЕКСТ РЫНКА СИНХРОНИЗИРОВАН",
        ["VISUAL"] = "ВИЗУАЛ",
        ["You"] = "Вы",
        ["desk query"] = "запрос",
        ["local crypto context"] = "локальный крипто-контекст",
        ["knowledge topic"] = "тема знаний",
        ["offline knowledge base"] = "офлайн база знаний",
        ["TOPIC"] = "ТЕМА",
        ["Visual Analysis"] = "Визуальный разбор",
        ["selected visual"] = "выбранный визуал",
        ["VISUAL ANALYSIS READY"] = "ВИЗУАЛЬНЫЙ РАЗБОР ГОТОВ",
        ["structured plan"] = "структурный план",
        ["TRADE PLAN READY"] = "ТОРГОВЫЙ ПЛАН ГОТОВ",
        ["This desk is fully functional in local mode. External multimodal model wiring is intentionally left disconnected for now."] = "Этот экран полностью работает в локальном режиме. Внешнее multimodal-подключение намеренно пока не включено.",
        ["Image viewing works in this panel now. User-upload image analysis will be enabled once the GPT bridge is connected."] = "Просмотр изображений уже работает в этой панели. Анализ пользовательских изображений включим после подключения GPT-моста.",
        ["Select a visual"] = "Выберите визуал",
        ["Choose a snapshot to inspect its context."] = "Выберите снимок, чтобы посмотреть его контекст.",
        ["Read open exposure, daily loss budget, and whether the active ticket is oversized for the current guardrail."] = "Смотрите открытую экспозицию, дневной лимит убытка и не превышает ли активная заявка текущие защитные рамки.",
        ["Shows wallet-to-quote-to-token flow for "] = "Показывает путь от кошелька через котируемый актив к токену для ",
        ["Visual scan mode for new-pair flow. Track readiness, slot pressure, and whether the session should stay selective."] = "Режим визуального сканирования потока новых пар. Следите за готовностью, давлением по слотам и за тем, нужно ли оставаться избирательным.",
        ["Explain the current setup, market structure, and what matters most right now."] = "Объясни текущий сетап, структуру рынка и что сейчас важнее всего.",
        ["Run a risk check on the active setup and tell me what can invalidate it."] = "Проведи проверку риска по активному сетапу и скажи, что может его сломать.",
        ["Explain the current DEX route, quote asset, and what can block execution."] = "Объясни текущий DEX-маршрут, котируемый актив и что может заблокировать исполнение.",
        ["Summarize sniper readiness, open slots, and whether the flow is hot or defensive."] = "Суммируй готовность sniper-модуля, открытые слоты и покажи, горячий сейчас поток или защитный.",
        ["Walk me through the selected visual and what it means for crypto execution."] = "Разбери выбранный визуал и объясни, что он значит для крипто-исполнения.",
        ["Give me the cleanest next action for this terminal state."] = "Подскажи самое чистое следующее действие для текущего состояния терминала.",
        ["Slippage is the gap between the quoted price and the actual fill. In this desk it matters most when spread widens, size is too large for available depth, or DEX liquidity is thin. If spread is elevated or the route looks fragile, prefer smaller size, staged entries, or a deeper limit instead of chasing market execution."] = "Проскальзывание — это разница между котируемой ценой и фактическим исполнением. В этом терминале оно особенно важно, когда расширяется спред, размер слишком велик для доступной глубины или DEX-ликвидность тонкая. Если спред повышен или маршрут выглядит хрупко, лучше уменьшить размер, входить поэтапно или ставить более глубокий лимитный ордер вместо погони за рынком.",
        ["Use market when speed matters more than precision and the spread is healthy. Use limit when the spread is wide, when you want a defined entry zone, or when you are sizing into thinner liquidity. In this terminal the assistant already watches spread, route readiness, and execution guards, so a blocked or defensive state usually argues for patience rather than a market sweep."] = "Рыночный ордер используйте, когда скорость важнее точности и спред нормальный. Лимитный ордер лучше подходит, когда спред широкий, нужна чёткая зона входа или вы заходите в более тонкую ликвидность. В этом терминале ассистент уже следит за спредом, готовностью маршрута и защитой исполнения, поэтому заблокированное или защитное состояние обычно говорит в пользу терпения, а не рыночного забора ликвидности.",
        ["A good stop should invalidate the trade idea, not just sit at an arbitrary percentage. Put it beyond the structure that would prove your premise wrong, then back-solve size from the allowed loss. If the stop has to be too wide for your risk budget, reduce size or skip the trade."] = "Хороший стоп должен ломать торговую идею, а не просто стоять на случайном проценте. Ставьте его за ту структуру, которая докажет неверность вашей гипотезы, а размер позиции уже считайте от допустимого убытка. Если стоп получается слишком широким для вашего бюджета риска, уменьшайте размер или пропускайте сделку.",
        ["Check route readiness, quote asset compatibility, wallet network match, liquidity quality, and whether execution is still paper-only. For fresh pairs also watch holder concentration, suspicious taxes, and whether sniper flow already looks overcrowded. A clean route alone is not enough if the token itself is structurally dangerous."] = "Проверьте готовность маршрута, совместимость котируемого актива, совпадение сети кошелька, качество ликвидности и не остался ли режим paper-only. Для свежих пар также смотрите на концентрацию держателей, подозрительные налоги и не выглядит ли поток sniper-модуля уже перегретым. Чистого маршрута недостаточно, если сам токен структурно опасен.",
        ["The best new-pair setups are not just fast, they are readable. You want healthy liquidity, manageable spread, a believable route, controlled slot pressure, and no obvious risk alarms. If the session is already stretched or consecutive losses are stacking, the right move is often to stay selective rather than force action."] = "Лучшие сетапы по новым парам не просто быстрые, а читаемые. Нужны здоровая ликвидность, управляемый спред, внятный маршрут, контролируемое давление по слотам и отсутствие явных риск-сигналов. Если сессия уже растянута или подряд копятся убытки, чаще правильнее оставаться избирательным, чем форсировать вход.",
        ["Use the chat desk to break down momentum, invalidation, risk, and execution for BTCUSDT."] = "Используйте этот чат, чтобы разбирать импульс, инвалидацию, риск и исполнение по BTCUSDT."
        ,
        ["ENTRY"] = "ВХОД",
        ["EXIT"] = "ВЫХОД",
        ["SNIPER"] = "SNIPER",

        // Alerts (in Settings)
        ["Telegram Notifications"] = "Уведомления Telegram",
        ["Telegram"] = "Telegram",
        ["Bot Token"] = "Токен бота",
        ["Chat ID"] = "ID чата",
        ["Test"] = "Тест",
        ["Add Alert"] = "Добавить алерт",
        ["Condition"] = "Условие",
        ["Threshold"] = "Порог",
        ["Repeat"] = "Повтор",
        ["+ Add"] = "+ Добавить",
        ["Sound on alert"] = "Звук при срабатывании",
        ["Active Alerts"] = "Активные алерты",
        ["Clear Fired"] = "Очистить сработавшие",
        ["Alert History"] = "История алертов",
        ["Fired At"] = "Время срабатывания",
        ["Clear"] = "Очистить",
        ["Alert Fired"] = "Алерт сработал",
        ["Note: VolumeSpike requires exchange volume data not available in the live stream."] = "Примечание: VolumeSpike требует данные объёма биржи, недоступные в потоке.",

        // TP / SL panel (Bots section)
        ["Take Profit / Stop Loss"] = "Тейк-профит / Стоп-лосс",
        ["Take Profit %"] = "Тейк-профит %",
        ["TP1 Close %"] = "TP1 Закрытие %",
        ["TP2 %"] = "TP2 %",
        ["Stop Loss %"] = "Стоп-лосс %",
        ["Trailing SL"] = "Скользящий SL",
        ["Trailing Stop %"] = "Trailing Stop %",
        ["Break-even Arm %"] = "Порог безубытка %",
        ["Futures: TP/SL placed as exchange orders (TakeProfitMarket / StopMarket) with ReduceOnly. Trailing SL replaces SL order on each new peak. Spot: monitored in-process."] = "Futures: TP/SL выставляются как биржевые ордера (TakeProfitMarket / StopMarket) с ReduceOnly. Trailing SL заменяет SL-ордер на каждом новом пике. Spot: мониторинг внутри процесса.",

        // Bots section
        ["Rule Bot Controls"] = "Управление правиловым ботом",
        ["Quantity"] = "Количество",
        ["Risk Cap"] = "Лимит риска",
        ["Market Mode"] = "Режим рынка",
        ["Margin"] = "Маржа",
        ["Bias"] = "Направление",
        ["Leverage"] = "Плечо",
        ["Start Bot"] = "Запустить бота",
        ["Stop Bot"] = "Остановить бота",
        ["Runtime"] = "Время работы",

        // Settings section
        ["Execution Defaults"] = "Настройки исполнения",
        ["Paper Only"] = "Только бумажный",
        ["PAPER ONLY"] = "ТОЛЬКО БУМАЖНЫЙ",
        ["Live Allowed"] = "Реальное разрешено",
        ["LIVE ALLOWED"] = "РЕАЛЬНОЕ РАЗРЕШЕНО",
        ["Wallet Session"] = "Сессия кошелька",
        ["Provider"] = "Провайдер",
        ["Network"] = "Сеть",
        ["Refresh Wallet"] = "Обновить кошелёк",
        ["Open Provider"] = "Открыть провайдер",
        ["Disconnect"] = "Отключить",
        ["DISCONNECT"] = "ОТКЛЮЧИТЬ",

        // Backtest section
        ["Equity Curve"] = "Кривая капитала",
        ["Net Return"] = "Чистая доходность",
        ["Win Rate"] = "Процент прибыльных",
        ["Max Drawdown"] = "Макс. просадка",
        ["Max DD"] = "Макс. просадка",
        ["Trade List"] = "Список сделок",
        ["Duration"] = "Длительность",
        ["Buy & Hold"] = "Купи и держи",
        ["Sharpe"] = "Коэффициент Шарпа",
        ["Strategy Comparison"] = "Сравнение стратегий",
        ["Load Candles"] = "Загрузить свечи",
        ["Commission %"] = "Комиссия %",
        ["Fast MA"] = "Быстрая MA",
        ["Slow MA"] = "Медленная MA",
        ["Run All Strategies"] = "Запустить все стратегии",
        ["Net Closed PnL"] = "Закрытый PnL",

        // Help / Logout
        ["Quick Start"] = "Быстрый старт",
        ["Safety"] = "Безопасность",
        ["Current Session State"] = "Состояние сессии",
        ["Safe Logout"] = "Безопасный выход",
        ["Open Dashboard"] = "Открыть дашборд",
        ["Open Logs"] = "Открыть логи",

        // Sniper exit engine
        ["Partial TP Trigger %"] = "Trigger TP1 %",
        ["Partial TP Sell %"] = "Закрыть на TP1 %",
        ["Auto-sell with take-profit when the price grows"] = "Авто-продажа при достижении тейк-профита",
        ["Cut the position automatically with stop-loss"] = "Автоматическое закрытие по стоп-лоссу",
        ["Protect gained profit with trailing stop"] = "Защита прибыли скользящим стопом",
        ["Arm break-even protection after a green move"] = "Включить защиту безубытка после роста",
        ["Enable partial take-profit runner"] = "Включить частичную фиксацию прибыли",
        ["Enable execution guard before buy"] = "Включить защиту исполнения перед покупкой",
        ["Enable full auto-buy on accepted pairs"] = "Включить полный авто-вход для принятых пар",
        ["Cooldown"] = "Задержка",
        ["Cooldown (sec)"] = "Задержка (сек)",

        // Backtest — ранее хардкодные русские строки
        ["Backtest Configuration"] = "Конфигурация бэктеста",
        ["By Date Range"] = "По датам",
        ["▶  Run"] = "▶  Запустить",
        ["Candles (max 3000)"] = "Свечей (макс 3000)",
        ["MA Fast (custom)"] = "MA Fast (пользов.)",
        ["MA Slow (custom)"] = "MA Slow (пользов.)",
        ["Start Date"] = "Дата начала",
        ["End Date"] = "Дата конца",
        ["Trades / Win Rate"] = "Сделок / Win Rate",
        ["Best / Worst Trade"] = "Лучш. / Худш. сделка",
        ["Strategy"] = "Стратегия",
        ["Same dataset. Sorted by return. Bold — custom strategy."] = "На одних данных. Сортировка по доходности. Жирным — пользовательская стратегия.",
        ["Trades"] = "Сделки",
        ["Best Trade"] = "Лучш. сделка",
        ["Opened"] = "Открыта",
        ["Closed"] = "Закрыта",
        ["Exit"] = "Выход",
        ["Net Return"] = "Чистая доходность",

        // DCA Bot
        ["DCA Bot"] = "DCA Бот",
        ["Interval"] = "Интервал",
        ["Period"] = "Период",
        ["Budget USDT"] = "Бюджет USDT",
        ["Run immediately on start"] = "Запустить сразу при старте",
        ["Cond. Buy"] = "Условная покупка",
        ["MA Days"] = "Дней MA",
        ["Avg Price / Held"] = "Средняя / В держании",
        ["Execution History"] = "История исполнений",
        ["Total USDT"] = "Итого USDT",
        ["+ Add Coin"] = "+ Добавить монету",
        ["Start DCA"] = "Запустить DCA",
        ["Stop DCA"] = "Остановить DCA",
        ["Run Now"] = "Запустить сейчас",
        ["Executing..."] = "Исполняется...",
        ["Hours"] = "Часов",
        ["Weeks"] = "Недель",
        ["Executed"] = "Исполнено",
        ["Skipped"] = "Пропущено",

        // Grid Trading Bot
        ["Grid Trading Bot"] = "Сеточный торговый бот",
        ["Lower Price"] = "Нижняя цена",
        ["Upper Price"] = "Верхняя цена",
        ["Grid Levels"] = "Уровней сетки",
        ["Qty / Grid"] = "Кол-во / ур.",
        ["Start Grid"] = "Запустить сетку",
        ["Stop Grid"] = "Остановить сетку",
        ["Pause"] = "Пауза",
        ["Resume"] = "Возобновить",
        ["Cycles Completed"] = "Циклов завершено",
        ["Grid P&L"] = "P&L сетки",
        ["Grid Spacing"] = "Шаг сетки",
        ["Set Lower < Upper to preview"] = "Установите Нижнюю < Верхней для предпросмотра",
        ["Running"] = "Работает",
        ["Stopped"] = "Остановлен",
        ["Paused"] = "Пауза",

        // Bybit Gateway / Exchange selector
        ["Exchange"] = "Биржа",
        ["Bybit API Keys"] = "API ключи Bybit",
        ["API Key (env)"] = "API ключ (env)",
        ["Key loaded"] = "Ключ загружен",
        ["No key — read-only"] = "Ключ не задан — только чтение",
        ["not set"] = "не задан",
        ["Set environment variables BYBIT_API_KEY and BYBIT_API_SECRET before launching."] =
            "Задайте переменные окружения BYBIT_API_KEY и BYBIT_API_SECRET перед запуском.",

        // P&L Dashboard
        ["Total P&L"] = "Общий P&L",
        ["Win Rate"] = "Win Rate",
        ["Avg Win"] = "Средн. выигрыш",
        ["Avg Loss"] = "Средн. убыток",
        ["Max Drawdown"] = "Макс. просадка",
        ["Profit Factor"] = "Profit Factor",
        ["Equity Curve"] = "Кривая эквити",
        ["P&L by Day"] = "P&L по дням",
        ["P&L by Source"] = "P&L по источнику",
        ["Trade History"] = "История сделок",
        ["↻ Refresh"] = "↻ Обновить",
        ["⬇ Export CSV"] = "⬇ Экспорт CSV",
        ["Period"] = "Период",
        ["Source"] = "Источник",
        ["No trade data yet. Complete a trade to see the equity curve."] =
            "Нет данных. Завершите сделку, чтобы увидеть кривую эквити.",

        // Whale Tracker
        ["Whale Tracker"] = "Whale Tracker",
        ["Whales"] = "Киты",
        ["Live Whale Alerts"] = "Живые whale-алерты",
        ["Tracked Wallets"] = "Отслеживаемые кошельки",
        ["Min Transfer"] = "Мин. перевод",
        ["Alerts Captured"] = "Алертов поймано",
        ["Labeled Wallet Alerts"] = "Алерты метк. кошельков",
        ["Start Tracking"] = "Запустить слежение",
        ["Stop Tracking"] = "Остановить слежение",
        ["Polling ETH · BSC · Solana"] = "Опрос ETH · BSC · Solana",
        ["Free keys increase rate limits from 1 req/5s to 5 req/s. Solscan uses public API."] =
            "Бесплатные ключи увеличивают лимит с 1 запроса/5с до 5 запросов/с. Solscan использует публичный API.",
        ["WATCHED"] = "МЕТКА",
        ["LARGE"] = "КРУПНЫЙ",

        // OKX Gateway
        ["OKX API Keys"] = "API ключи OKX",
        ["Set environment variables OKX_API_KEY, OKX_API_SECRET and OKX_API_PASSPHRASE before launching."] =
            "Задайте переменные окружения OKX_API_KEY, OKX_API_SECRET и OKX_API_PASSPHRASE перед запуском.",
        ["Passphrase"] = "Пароль",
        ["Passphrase set"] = "Пароль задан",
        ["Passphrase not set"] = "Пароль не задан",

        // Funding Rate Monitor
        ["Funding Rates"] = "Ставки финансирования",
        ["Funding History"] = "История финансирования",
        ["Extreme Rate Alerts"] = "Алерты экстремальных ставок",
        ["All Instruments"] = "Все инструменты",
        ["Extremes only"] = "Только экстремальные",
        ["Start"] = "Старт",
        ["RATE"] = "СТАВКА",
        ["ANNL."] = "ГОДОВЫХ",
        ["MARK $"] = "МАРК $",
        ["NEXT"] = "СЛЕД.",
        ["AVG FUNDING"] = "СР. ФИНАНСИР.",
        ["EXTREME INSTRUMENTS"] = "ЭКСТРЕМАЛЬНЫХ",
        ["TOP LONG FUNDING (best short)"] = "МАКС. СТАВКА (шорт-арбитраж)",
        ["TOP SHORT FUNDING (best long)"] = "МИН. СТАВКА (лонг-арбитраж)",
        ["No extreme rates detected yet."] = "Экстремальных ставок пока нет.",
        ["(click row to switch)"] = "(клик для выбора)",
        ["No history data — select a symbol or refresh"] = "Нет истории — выберите инструмент",

        // Token Security Scanner
        ["Deep security scan before buy (GoPlus + Honeypot.is / RugCheck)"] =
            "Глубокая проверка безопасности перед покупкой (GoPlus + Honeypot.is / RugCheck)",
        ["Likely Safe"] = "Вероятно безопасен",
        ["Moderate Risk"] = "Умеренный риск",
        ["High Risk"] = "Высокий риск",
        ["Dangerous"] = "Опасен",
        ["Not scanned"] = "Не проверен",
        ["No flags"] = "Флаги отсутствуют",
        ["Honeypot"] = "Honeypot",
        ["Mintable"] = "Mintable",
        ["Blacklist function"] = "Функция блокировки",
        ["Owner not renounced"] = "Владелец не отказался",
        ["Renounced"] = "Отказался",
        ["Owner active"] = "Владелец активен",
        ["Hidden owner"] = "Скрытый владелец",
        ["Proxy contract"] = "Прокси-контракт",
        ["Self-destruct"] = "Самоуничтожение",
        ["Score"] = "Оценка",
        ["🔍 Scanning contract security…"] = "🔍 Проверка безопасности контракта…",

        // Common UI labels
        ["Active"] = "Активный",
        ["Balance"] = "Баланс",
        ["Change"] = "Изменение",
        ["Last"] = "Последняя",
        ["Mode"] = "Режим",
        ["Stop"] = "Стоп",
        ["Target"] = "Цель",
        ["Selection"] = "Выбор",
        ["Amount"] = "Сумма",
        ["Available Balance"] = "Доступный баланс",
        ["Leverage / Mode"] = "Плечо / Режим",
        ["Position Sizing"] = "Размер позиции",
        ["PAPER"] = "БУМАЖНЫЙ",

        // Gas Monitor (Feature 14)
        ["Gas Monitor"] = "Монитор комиссий",
        ["Network Fees Monitor"] = "Монитор сетевых комиссий",
        ["ETH Gas"] = "Газ ETH",
        ["BSC Gas"] = "Газ BSC",
        ["Solana Network"] = "Сеть Solana",
        ["Slow"] = "Медленно",
        ["Standard"] = "Стандартно",
        ["Fast"] = "Быстро",
        ["ETH Alert Threshold (gwei)"] = "Порог алерта ETH (gwei)",
        ["BSC Alert Threshold (gwei)"] = "Порог алерта BSC (gwei)",
        ["Refresh"] = "Обновить",
        ["No data yet — press Refresh"] = "Нет данных — нажмите Обновить",
        ["Low gas alert — great time for large swaps"] = "Газ низкий — хороший момент для крупных свопов",
        ["Gas history (ETH Standard, last 60 polls)"] = "История газа ETH (стандартный, 60 замеров)",
        ["Alert: Gas dropped below threshold"] = "Алерт: газ упал ниже порога",

        // All Positions (Feature 15)
        ["All Positions"] = "Все позиции",
        ["Unified Positions"] = "Сводные позиции",
        ["Total Unrealized PnL"] = "Суммарный нереализованный P&L",
        ["Notional"] = "Номинал",
        ["Close All"] = "Закрыть всё",
        ["Close Position"] = "Закрыть позицию",
        ["No open positions found"] = "Открытых позиций не найдено",
        ["Refreshing positions…"] = "Обновление позиций…",
        ["Emergency exit — closing position(s)…"] = "Аварийный выход — закрытие позиций…",
        ["Sort by PnL%"] = "Сортировка по PnL%",
        ["Sort by Size"] = "Сортировка по размеру",
        ["Sort by Exchange"] = "Сортировка по бирже",
        ["EXCHANGE"] = "БИРЖА",
        ["ENTRY"] = "ВХОД",
        ["MARK"] = "МАРК",
        ["LIQ."] = "ЛИК.",
        ["UNREAL. PNL"] = "НЕРЕАЛ. P&L"
    };

    private readonly (string Prefix, string Translation)[] _prefixTranslations =
    [
        ("Updated: ", "Обновлено: "),
        ("Remaining: ", "Осталось: "),
        ("Offset ", "Смещение "),
        ("Token: ", "Токен: "),
        ("DEX: ", "DEX: "),
        ("Bid: ", "Bid: "),
        ("Ask: ", "Ask: "),
        ("Vol $ ", "Объём $ "),
        ("Loading: ", "Загрузка: "),
        ("Total ", "Всего "),
        ("Session Buys", "Покупки за сессию"),
        ("Take Profit: ", "Тейк-профит: "),
        ("Updated ", "Обновлено "),
        ("Workspace ", "Рабочее пространство "),
        ("Trend snapshot for ", "Снимок тренда для "),
        ("Open ", "Открыто "),
        ("Win ", "Побед "),
        ("Net ", "Результат "),
        ("Local runtime ", "Локальный runtime "),
        ("Talk through DEX execution, route readiness, token context, and sniper overlays for ", "Разберите DEX-исполнение, готовность маршрута, контекст токена и sniper-оверлеи для "),
        ("Total: ", "Итого: ")
    ];

    private UiLocalizationService()
    {
    }

    public static UiLocalizationService Instance { get; } = new();

    public UiLanguage CurrentLanguage { get; private set; } = UiLanguage.English;

    public event EventHandler? LanguageChanged;

    public bool IsRussian => CurrentLanguage == UiLanguage.Russian;

    public void SetLanguage(UiLanguage language)
    {
        if (CurrentLanguage == language)
        {
            return;
        }

        CurrentLanguage = language;
        LanguageChanged?.Invoke(this, EventArgs.Empty);
    }

    public string Translate(string text)
    {
        if (string.IsNullOrWhiteSpace(text) || CurrentLanguage == UiLanguage.English)
        {
            return text;
        }

        var lines = text.Split(Environment.NewLine);
        return string.Join(
            Environment.NewLine,
            lines.Select(TranslateSingleLine));
    }

    private string TranslateSingleLine(string text)
    {
        if (_englishToRussian.TryGetValue(text, out var direct))
        {
            return direct;
        }

        foreach (var (prefix, translation) in _prefixTranslations)
        {
            if (text.StartsWith(prefix, StringComparison.Ordinal))
            {
                return translation + text[prefix.Length..];
            }
        }

        return text;
    }
}
