<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CryptoAITerminal.Executor</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CryptoAITerminal.Server.Data\CryptoAITerminal.Server.Data.csproj" />
    <ProjectReference Include="..\CryptoAITerminal.Server.Common\CryptoAITerminal.Server.Common.csproj" />
    <ProjectReference Include="..\CryptoAITerminal.Core\CryptoAITerminal.Core.csproj" />
    <ProjectReference Include="..\CryptoAITerminal.Gateway.Binance\CryptoAITerminal.Gateway.Binance.csproj" />
    <ProjectReference Include="..\CryptoAITerminal.Gateway.Bybit\CryptoAITerminal.Gateway.Bybit.csproj" />
    <ProjectReference Include="..\CryptoAITerminal.Gateway.OKX\CryptoAITerminal.Gateway.OKX.csproj" />
    <ProjectReference Include="..\CryptoAITerminal.Gateway.KuCoin\CryptoAITerminal.Gateway.KuCoin.csproj" />
  </ItemGroup>

</Project>
