<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CryptoAITerminal.Server.Data</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="8.0.3" />
    <PackageReference Include="Dapper" Version="2.1.35" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CryptoAITerminal.Core\CryptoAITerminal.Core.csproj" />
    <ProjectReference Include="..\CryptoAITerminal.Server.Common\CryptoAITerminal.Server.Common.csproj" />
  </ItemGroup>

</Project>
