<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CryptoAITerminal.Server.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CryptoAITerminal.Server.Data\CryptoAITerminal.Server.Data.csproj" />
    <ProjectReference Include="..\CryptoAITerminal.Server.Common\CryptoAITerminal.Server.Common.csproj" />
  </ItemGroup>

</Project>
